### ISSUE TITLE
Question: How to automatically set the width

### ISSUE THREAD

**Issue by taylorh140** [FHPythonUtils/AnsiToImg#15]
I have some flow charts and renders and I would like them to not have to wrap issues. is there a way to detect the width appropriately?
![image](https://github.com/FHPythonUtils/AnsiToImg/assets/10996543/94438bf3-9e44-437f-bf00-9d5d22935c03)

**Comment by FredHappyface** [comment]
Hi I explored adding this functionality today and it is not feasible as the underlying render lib Textualize/rich doesn't behave as expected. I'd suggest setting an explicit width with the `width` parameter :)

**Comment by taylorh140** [comment]
Fair enough. :)
thanks!
