### ISSUE TITLE
Feature: Add width + Height params

### ISSUE THREAD

**Issue by punctuations** [FHPythonUtils/AnsiToImg#4]
Please add a parameter for width + height for larger ansi art, as the terminal size limits it and makes the project unusable as a library.

Here is where the width + height should be determined by the user: https://github.com/FHPythonUtils/AnsiToImg/blob/master/ansitoimg/render.py#L25-L28

Here's an example of the issue:

![](https://user-images.githubusercontent.com/37005919/175111885-5e52bfc3-ad5f-41f9-bcad-3edebd6b8ea8.png)

**Comment by jaxdasnac** [comment]
I am having the same issue

**Comment by FredHappyface** [comment]
Hi thanks for opening the issue and the PR too. Agreed that this was an oversight in initial dev. I've dropped a handful of comments, once addressed I'd be happy to merge 

I've a few thoughts around some features I'll work on once that's sorted as I certainly have a couple minor pain points using the lib

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/AnsiToImg/commit/fd1666e3f99c862270cfea0b448000a111847eb9
