### ISSUE TITLE
Feature: custom width from the CLI

### ISSUE THREAD

**Issue by noraj** [FHPythonUtils/AnsiToImg#6]
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

Have the ability to choose width size from the CLI tool.

### Describe the solution you'd like

Now that #4 is fixed thanks to fd1666e3f99c862270cfea0b448000a111847eb9, it should be easy to replace the `--wide` option that just make the fixed width move from 49 to 89 pixel with `--width <size>` where we would be able to provide a custom width.

`--wide, -w            Use a 'wide' virtual terminal (89 chars vs 49)`

**Comment by FredHappyface** [comment]
Hey cheers for this

Replacing wide with a width arg would be ideal however, I've got to assume that people are consuming the current interface. So what I'll do is implement a width as another arg and aim to mark "wide" as deprecated

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/AnsiToImg/releases/tag/2023.1
