### ISSUE TITLE
Miss a real example in README

### ISSUE THREAD

**Issue by jedie** [FHPythonUtils/AnsiToImg#8]
Think it's a good idea to add a real example into README, how to use it.
Something like this:
```
pipx install ansitoimg
ls --color=always /etc | ansitoimg ls.svg
git diff --color=always | ansitoimg diff.svg
```

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/AnsiToImg/commit/ba0080203d2fe153b1269aa5f3a4daed5df300fc
